# hello yaoyuan 1
proxy-providers:
  touhou-provider:
    type: http
    path: ./touhou.yaml
    url: "https://api.touhou.center/link/i5TgtSuyw1tH2snv?clash=1"
    interval: 3600
proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - DIRECT
      - è‡ªå»ºèŠ‚ç‚¹1
      - è‡ªå·±èŠ‚ç‚¹2
    use:
      - touhou-provider